# Generated by Django 3.2.8 on 2021-11-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default={'ru': '', 'uz': ''})),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default={'ru': '', 'uz': ''})),
                ('price', models.IntegerField()),
                ('price_type', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('RUB', 'RUB')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('size', models.JSONField(default={'heigth': '', 'length': '', 'width': ''})),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mebel_site.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mebel_site.product')),
            ],
        ),
    ]
